### ISSUE TITLE
A way to save the posts before shredding them?

### ISSUE THREAD

**Issue by pteek** [x89/Shreddit#25]
So we can have a personal account of the history. Self-posts, links and comments.

This should be fairly easy to implement.

**Comment by x89** [comment]
What format do you mean? At the moment I have a cron job that saves the output (when `verbose = True`) to a dated text file and that's sufficient for my use case.

Do you mean a single file? SQLite database?

**Comment by pteek** [comment]
I am working on a solution by serializing the json_dict as json in txt files. It's good enough for me.

**Comment by pteek** [comment]
Test please https://github.com/pteek/Shreddit

**Comment by x89** [comment]
It looks good on the surface. One thing though, the comment "Saving a copy" should only be printed if keep_a_copy is true (otherwise it's confusing to users that don't have it enabled, and as the primary aim of the program is deleting the user should be informed when it happens regardless.)

**Comment by x89** [comment]
Throw up a PR if you want me to check it over and incorporate it into here!
