### ISSUE TITLE
Problems on windwos.

### ISSUE THREAD

**Issue by pteek** [x89/Shreddit#26]
No get_sentence defined if platform is not posix.
https://github.com/x89/Shreddit/blob/master/shreddit.py#L18

Also, thing.created_utc is not in utc.
https://github.com/x89/Shreddit/blob/master/shreddit.py#L108

What is the logic behind this?
https://github.com/x89/Shreddit/blob/master/shreddit.py#L117-L120

**Comment by x89** [comment]
1) It should be defined now.
2) How far off is created_utc?
3) The logic is if you choose not to delete comments but only edit them then you don't want to be re-editing them every time you run the script. It's probably beyond the scope of the program to be honest - it was added as an experiment but I'd be surprised if anybody uses it.

**Comment by pteek** [comment]
2) it's off by my timezone. So it's some config.
3) Does it handle the fact that a comment may have been edited for real and it is not shredded(filled with garbage) yet?

I am doing some other changes too. I'll send a PR if I am done first.

**Comment by pteek** [comment]
Okay, created_utc actually shows the time that I see in my browser. So it basically shows me time in my time zone where it is supposed to be UTC.

**Comment by x89** [comment]
It'd be very hard to check for edited-by-shreddit vs edited-by-user as there are various methods of replacing your text before deletion. That said at the moment it's not even checking the `thing.edited` flag at the moment, it's basing it on time differences.

As I mentioned it's a bit of a scrappy feature to be honest, possibly worth throwing out.
