### ISSUE TITLE
SSL doesn't work

### ISSUE THREAD

**Issue by fu9ar** [x89/Shreddit#28]
I had to shut it off in the reddit browser app, but otherwise it works great.

I forgot to grab the python stackdump for you, but it topped out in urllib3. Let me know if you need it.

Also, otherwise, I'm on a bass-ackwards Slackware box, so I installed pip and added your libs manually from my root shell and everything worked swimmingly!

**Comment by x89** [comment]
Oh it's been a while since I've met a Slacker! If you're happy with that
then I'm happy.

I'll take another look at the SSL issue in a couple of hours, just waking
up. *Yawn*.

**Comment by fu9ar** [comment]
bash-4.2$ python shreddit.py -c shreddit.cfg.example 
/usr/lib64/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Logged in as kevin_fu9ar
Deleting messages before 2015-04-13 00:57:57.353769.
Keeping messages from subreddits

**Comment by x89** [comment]
Upstream problem, one requires to use PRAW 3 (branch on the PRAW repo).

See:
* https://www.reddit.com/r/redditdev/comments/2gmzqe/praw_https_enabled_praw_testing_needed/
* https://github.com/praw-dev/praw/issues/353
