### ISSUE TITLE
Edits/deletes ~100 comments and then stops

### ISSUE THREAD

**Issue by YPCrumble** [x89/Shreddit#31]
I started the process and it runs fine but only gets through ~100 comments/posts each time and then stops. I then have to restart it and it continues where it left off. It seems like the call things = r.user.get_overview(limit=None, sort=sort) isn't actually getting all of the comments/submissions for some reason...it looks like an issue with https://praw.readthedocs.org/en/v2.1.21/pages/code_overview.html#praw.__init__.BaseReddit.get_content in which get_content() isn't actually doing "If limit is None, then fetch as many entries as possible (reddit returns at most 100 per request, however, PRAW will automatically make additional requests as necessary)."

Is there a testing module or dummy dataset to replicate the issue perchance?

**Comment by ryanvarley** [comment]
I can confirm the issue, i had to run the script multiple times to wipe everything

**Comment by x89** [comment]
I've pushed a change that should fix this, barring pretty extreme edge cases.
It just counts the number of removed items, and if it was greater than one it iterates over them again.

https://github.com/x89/Shreddit/commit/9b1c0663f8b89221391e738c246d96dd4f6706b2

There are better ways of doing this but not without frustratingly repetitive code — and I don't think this warrants going into so much depth. I'd be more inclined to clean up the code by removing things that people probably aren't using (like edit_only mode).

Thoughts?

**Comment by YPCrumble** [comment]
@x89 I like it - does the same thing as I would do manually to work around it...thank you for writing it!

**Comment by x89** [comment]
Alright fantastic, well I'll call it closed! Thanks for the feedback. <3
