### ISSUE TITLE
Breaks when Encountering Accented Character is Post Title

### ISSUE THREAD

**Issue by armastudios** [x89/Shreddit#32]
I haven't confirmed this but, if I could venture a guess. The post being deleted had an "â" in the title. I deleted it manually and shreddit was able to resume.

>Traceback (most recent call last):
 > File "shreddit.py", line 143, in <module>
>    url=thing.url)
>UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 59: ordinal not in range(128)

**Comment by x89** [comment]
Hmm. Seems to have been a problem with the URL, it bummed out on a submission so I'm guessing the URL contained a unicode character? What happens if you try using the latest version, that should encode it correctly.

**Comment by armastudios** [comment]
Looks like it's working now, 

> Deleting submission: #37anxl http://www.reddit.com/r/test/comments/37anxl/ééééé/

The post with the accented character in the title/url was deleted successfully. Thanks!
