### ISSUE TITLE
Not removing all the reddit comments

### ISSUE THREAD

**Issue by noflag** [x89/Shreddit#35]
It only does a few. I want to delete my total reddit history

**Comment by x89** [comment]
Latest revision? Any idea how many a few is?

On holiday atm so won't be pushing code changes but I'll take a look on
Monday.

**Comment by noflag** [comment]
It seems to be removing 35 comments each run

**Comment by noflag** [comment]
It seems random, I got 35, 100, 16, 

Found with python shreddit.py -c shreddit.cfg | grep -c Editing

**Comment by x89** [comment]
Hmm. The latest change was supposed to fix this problem by iterating over the get_comments() various times (it's what the loop at the end is for).

I'll look into it in a bit.

**Comment by denizdogan** [comment]
@noflag I have forked the repo including the fix and created a pull request for it: https://github.com/x89/Shreddit/pull/38

**Comment by x89** [comment]
Thanks very much @denizdogan, your contribution is appreciated!
