### ISSUE TITLE
Depreciation warning when running

### ISSUE THREAD

**Issue by noflag** [x89/Shreddit#36]
/usr/local/lib/python2.7/dist-packages/praw/decorators.py:88: DeprecationWarning: reddit intends to disable password-based authentication of API clients sometime in the near future. As a result this method will be removed in a future major version of PRAW.

For more information please see:

* Original reddit deprecation notice: https://www.reddit.com/comments/2ujhkr/

* Updated delayed deprecation notice: https://www.reddit.com/comments/37e2mv/

Pass ``disable_warning=True`` to ``login`` to disable this warning.
  warn(msg, DeprecationWarning)

**Comment by x89** [comment]
I don't know if disabling warnings is a good solution to this, I'd rather people migrated to Oauth2 (I wrote a script to do so).

A better alternative is `2>/dev/null` to stop the display of warnings (which is what you're doing anyway). I prefer this to the alternative.
