### ISSUE TITLE
Insecure platform warning on launch

### ISSUE THREAD

**Issue by noflag** [x89/Shreddit#37]
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by x89** [comment]
Looks like an upstream problem with PRAW? Shreddit doesn't call urllib3 directly, not in the most recent version though (there's an old branch that does).

**Comment by psykzz** [comment]
its new in urllib3 yes, there is a way to disable it if you understand the risks.

**Comment by x89** [comment]
Closing this as it's upstream, it's a pain and how I've been dealing with it is redirecting `STDERR`. Not ideal but it should be fixed in future versions of Python / urllib3.

**Comment by psykzz** [comment]
The issue here is its not going to be fixed, the warning is there for a reason. If you know what your doing and proceeding you can mute the warning as they suggest in the article.

**Comment by x89** [comment]
Do you think it better to leave the warnings enabled, use custom logging or to disable warnings entirely?

If custom logging how would you go about it for this project?

**Comment by x89** [comment]
I believe that's the error gone now, for me anyway (Python 3.5.0 / praw 3.3.0).

Let me know if it's still throwing it.
