### ISSUE TITLE
OAuth get_secret.py Upgrade

### ISSUE THREAD

**Issue by Fscked-In-The-Head** [x89/Shreddit#40]
Running get_secret.py gives a syntax error.
I might just be an idiot, but I can't seem to find a way around this. I'd like to upgrade to OAuth before it stops being supported by Reddit.

```shell
python get_secret.py 
Traceback (most recent call last):
File "get_secret.py", line 18, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

**Comment by x89** [comment]
Can you let me know if the latest push helped? Which python version are you
running?

It looks like it's something in asyncio which was an import we weren't
using anyway so I've gone and removed it.


(I'll be gone until Friday but I'll take a look then if that hasn't fixed
it)

**Comment by Fscked-In-The-Head** [comment]
Perfect, that fixed it! What was asyncio destined to be used for?

Thanks,
FITH

**Comment by Fscked-In-The-Head** [comment]
Hmm. Now it runs, but doesn't refresh the OAuth token properly. When I run get_secret.py after adding the refresh token to praw.ini, it attempts to reauthorize.
