### ISSUE TITLE
Remove upvoted/downvoted history

### ISSUE THREAD

**Issue by noflag** [x89/Shreddit#41]
Thanks! This project has been really cool so far.

**Comment by x89** [comment]
Just out of interest why would you use this option? It's been included for a while but I don't actually see any use for it to be quite honest!

https://github.com/x89/Shreddit/blob/master/shreddit.cfg.example#L23

**Comment by noflag** [comment]
just to remove the history from the profile page. i want to remove my up/downvote history on posts I don't own
