### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by norrism** [x89/Shreddit#44]
Traceback (most recent call last):
  File "shreddit.py", line 195, in <module>
    remove_things(get_things())
  File "shreddit.py", line 159, in remove_things
    content = str(content).encode('ascii', 'ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 25: ordinal not in range(128)

I'm getting this error for every account I've tried. Does anyone have a solution?

**Comment by x89** [comment]
It doesn't even look like that line is even used…

Try removing it and look again.

**Comment by x89** [comment]
@norrism any luck?
