### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bisherbas** [x89/Shreddit#45]
Upon executing the script, following message shows in Terminal:

INFO:__main__:Logged in as [username]

No other messages are shown and when I visit reddit I see that none of the comments or submission are deleted.

Running El-Capitan. Followed the instructions on the repository homepage and satisfied all the Python requirements.

verbose is set to True.

**Comment by CaptainMcCrank** [comment]
You have to set trial_run = false in your cfg file.

**Comment by x89** [comment]
Going to assume @CaptainMcCrank was correct and close this issue.

**Comment by ODyckhoff** [comment]
Sorry to comment on a closed issue, but I have this problem. Verbose mode is on, and with or without trial run, no output is given to suggest that any posts would or wouldn't have been edited/deleted. Logging in works OK. I used get_secret.py to authorize the script to access my account successfully.

Output below:

    owen@owen $ source ./bin/activate
    (Shreddit-master)owen@owen $ python3 shreddit.py -c shreddit.cfg
    WARNING:__main__:You should migrate to OAuth2 using get_secret.py before             Reddit     disables this login method.
    /usr/local/lib/python3.3/dist-packages/praw/decorators.py:74: DeprecationWarning: reddit intends to disable password-based authentication of API clients sometime in the near future. As a result this method will be removed in a future major version of PRAW.

    For more information please see:
    
    * Original reddit deprecation notice: https://www.reddit.com/comments/2ujhkr/
    
    * Updated delayed deprecation notice: https://www.reddit.com/comments/37e2mv/
    
    Pass ``disable_warning=True`` to ``login`` to disable this warning.
      warn(msg, DeprecationWarning)
    INFO:__main__:Logged in as ijzerengel.
    (Shreddit-master)owen@owen $

I'd be grateful for any suggestions what I might be doing wrong.

**Comment by benwritescode** [comment]
Hi. I'm getting this same result, plus a few warnings about unclosed socket streams. I do have trial_run = True. However, shouldn't it still save comments in a trial run? I was hoping to see it save the comments before I disable the trial run.
