### ISSUE TITLE
How to get password-based authentication of API?

### ISSUE THREAD

**Issue by JulianNorton** [x89/Shreddit#46]
It's not clear based on the information provided how to remove the warning. The error says normal login will be disabled, but the reddit thread link states:

> we will **not** be forcing the swap.

I understand why 2 factor is important, but I'm not sure what steps I need to take to not get the warning at all.

Secondly, I'm not sure how to disable the warning. Where do I pass the flag? I've tried in both my config file and praw.ini and I'm still getting the warning.

**Comment by x89** [comment]
I'm also not sure if the warning will go or not, if Reddit continues to offer password (cookie) based authentication then that's fine. The warning can be suppressed through your $SHELL, though I advise just upgrading via the `get_secret.py` option, that stops the warning and removes your password from the script.

It's an upstream issue with praw if you want to suppress the warning that it outputs.
