### ISSUE TITLE
Comments not saved in trial run

### ISSUE THREAD

**Issue by e1hd983** [x89/Shreddit#48]
I am trying a trial run of shreddit. Used OAuth2/ created a script linked to my reddit account, and the warning messages about authentication went away. But during the trial run, it seems much too fast (like 15 seconds or less), and no comments are saved in the save directory I specified in my config. Is this because it doesn't access the web at all during a trial run? Or is something else not working? 

I did save all my comments by hand, just in case, but I really would like getting a better save in .json format from the script.

Thanks!

**Comment by rtgibbons** [comment]
Hey, stumbled on this looking for another issue. 

When in trail_run, the code for saving to a directory doesn't get run https://github.com/x89/Shreddit/blob/master/shreddit.py#L157-L166

If you were to move the save_directory before the trail_run then they would get saved before.

**Comment by x89** [comment]
I thought that would be the case, if you submit a pr or leave me to do it
I'll get it done.
