### ISSUE TITLE
Tried to run with pycharm, got 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by vizakenjaro** [x89/Shreddit#51]
I placed shreddit.cfg and shreddit.py on the desktop folder (OS X).
Then run it under IDE environment called PyCharm.
Installed modules yaml and praw.

Got error:
(line 50 in shreddit.py)
config.read(args.config)
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by x89** [comment]
Pulled to latest?

**Comment by vizakenjaro** [comment]
What?

**Comment by kevinhikaruevans** [comment]
It looks like config is just set to `None` right before `read` is called. 

I ran it without the `-c shreddit.yml` args and it worked for me (`python ./shreddit.py` instead of `python ./shreddit.py -c shreddit.yml`)...

**Comment by x89** [comment]
Ah I maybe missed something there, will check later.

**Comment by Tjololo12** [comment]
Looks like a simple fix. I edited the code and changed:

`config = None
if args.config:
    config.read(args.config)
else:
    with open('shreddit.yml', 'r') as fh:
        config = yaml.safe_load(fh)
if config is None:
    raise Exception("No config options passed!")`

to:

`config = None
if args.config:
    with open(args.config, 'r') as fh:
      config = yaml.safe_load(fh)
    #config.read(args.config)
else:
    with open('shreddit.yml', 'r') as fh:
        config = yaml.safe_load(fh)
if config is None:
    raise Exception("No config options passed!")`

Note that adding the "with open(args.config, 'r' as fh:" line will open the config file you pass.

**Comment by cereal-killer** [comment]
Hey there, this should be fixed by #54

**Comment by x89** [comment]
Merged (can't test at the moment but looks like it should work).

Pull again @vizakenjaro and see if that works for you.

Thanks as well @Tjololo12.
