### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by rtgibbons** [x89/Shreddit#52]
It'd be awesome to have something like https://github.com/christophercliff/tweet-lifetime for this. So a simple deploy to heroku, enter basic config, and then your are off to the races.

If there is interest in this let me know and I'll try to help. I'm not a web python dev so I'm not sure what all would be needed. My guess is we could create a basic web server with a timer built in that executes "runners" to this script. From the above repo, they are using a plugin to keep the dyno from sleeping, and providing the uptime, other then that it just executes the runner as needed.

Another option would be to look at https://elements.heroku.com/addons/scheduler

**Comment by x89** [comment]
I've been thinking of setting up a web service where people can fine tune (basically configure the config) and it'd have a queue running in the background checking every second for any posts to be removed.

You're welcome to look into the Heroku option but I like the idea of running a Shreddit queue — it would also solve the problem of OAuth2 being a PITA to set up for individual accounts, and requiring re-setting-up on new Reddit accounts.

**Comment by x89** [comment]
To be honest I don't think I'll use Heroku, though if somebody else wants to I'm not against it.

I'd prefer to create a service using a VPS / AWS if going for a self-hosted option.
