### ISSUE TITLE
When you edit a comment, can you not replace it with spam?

### ISSUE THREAD

**Issue by Halnex** [x89/Shreddit#55]
I just used your script to remove all my comments and posts and it works like a clock.

Thank you for creating it.

However, in the process, I have tripped the alarm of /r/conspiracy (and potentially other subreddits too) and I have been banned from there.

I had to message them and explain to them what was going on, they were understanding and removed the ban.

So is it possible to not replace the original comments with spam? Just replace them with `.` (a dot) or would that change how reddit treats comments and edits?

**Comment by x89** [comment]
If you take a look at the current line 26 in Shreddit.py you may be able to use that. But I can easily add a few options (random, dot, string, no change, …) to the config file, I'll look into that now.

Change line: https://github.com/x89/Shreddit/blob/master/shreddit.py#L26

**Comment by x89** [comment]
https://github.com/x89/Shreddit/commit/3fcbfb101a03927537050da4626fcfbc0799c0eb

This change should fix it. Remember to add the additional section to your `shreddit.yml`!
