### ISSUE TITLE
Whitelist/Blacklist subreddits with multireddit lists?

### ISSUE THREAD

**Issue by noflag** [x89/Shreddit#59]
It would be great if I could add subreddits to a multireddit list and have it included or excluded in shreddit. Does the api support listing the subreddits in a multireddit list?

**Comment by x89** [comment]
I personally don't use multireddits at all, I wouldn't have thought it too hard to just fill them out?

Though I believe PRAW does support multireddit calls, I could throw together a short script that would output all the subreddits in a multireddit to be used in your config file?

It's a feature that could be added I suppose but I'm quite loathe to add it unless there's high demand for it. It's something very niche that would complicate the main program and config.

**Comment by scott-hand** [comment]
@noflag It's been a while, but I just added this. Take a look at the README for up to date installation info and let me know if it works for you. Probably best to run it in trial_run mode first to be safe.
