### ISSUE TITLE
OAuth2 not working

### ISSUE THREAD

**Issue by Hebury** [x89/Shreddit#62]
I'm just missing something really obvious probably, but I've stared at this for 30 minutes now and I still haven't figured it out.
I did the setup process for OAuth2, but it still seems to be using the username and password in my config.yml file. If I leave those empty it will prompt me for my username and pw. 

Notes:
- If I specify in my config.yml everything works fine
- My praw.ini setup went succesfully, I have a oauth_refresh_token in praw.ini

It just seems to me that I need to add a argument to make it use the praw.ini OAuth2 data instead of the config.yml username and password data.

What am I doing wrong? 

shredditcfg.yml:
> ---
> username:
> password:
> hours: 168
> max_score: 300
> sort: new
> verbose: True
> clear_vote: False
> item: overview
> whitelist: [AskScience, TheCulture, redditdev, programming, charity, netsec]
> whitelist_ids: []
> trial_run: False
> edit_only: False
> whitelist_distinguished: True
> whitelist_gilded: True
> nuke_hours: 720
> keep_a_copy: True
> save_directory: C:\Users\Rubeb\Documents\Reddit backup
> replacement_format: "Leave no evidence"
> vim: syntax=yaml ts=2

**Comment by x89** [comment]
On line 20 can you set it to `log.setLevel(level=logging.DEBUG)` and paste whether it says something like:

```
DEBUG:__main__:Logged in with OAuth.
INFO:__main__:Logged in as xxxxxxx
```

**Comment by Hebury** [comment]
I don't know how dumb I have been but I just retested this and it's not asking for my password anymore and it's says "DEBUG:__main__:Logged in with OAuth." 
So everything is working perfectly, sorry to have been a bother. 
Cheers

**Comment by x89** [comment]
Glad to hear it!
