### ISSUE TITLE
Issue using/installing on windows.

### ISSUE THREAD

**Issue by joebywan** [x89/Shreddit#70]
So I followed the windows installation instructions installing python 3.5, but the command pip install -U shreddit-master.zip didn't work as it couldn't find pip in the path (even after a system reboot).

I did some searching and found it in the python/scripts folder.  I navigated to there and used the command to avoid path issues, which seemed to do some stuff saying it'd installed shreddit & downloading some dependencies.

I then tried looking for the shreddit.yml.example to edit as per your instructions, but couldn't.  So I tried editing it in the zip file and then installing again, no luck.

To get it finding the shreddit.yml I pasted a copy into the python/scripts folder and it found it, but then gave me the error of 

```
yaml.parser.ParserError: expected '<document start>', but found '<block mapping
start>'
  in "shreddit.yml", line 14, column 1
```

So I'm not sure how to get over this hurdle.  Any ideas?

**Comment by x89** [comment]
Hi @joebywan,

It seems to be on stage 3 that you're getting stuck correct?

> 3. Open command prompt to the folder with the zip file (Shreddit-master.zip), and type pip install -U Shreddit-master.zip

I wonder if I could ping @scott-hand as I believe he has a Windows machine at his disposal while I'd have to set up a VM for this if I can't work it out myself.

Can I check that you added your username and password to your `shreddit.yml` as well? And if you wouldn't mind could you paste it here (removing the user and pass of course).

Thanks!

**Comment by joebywan** [comment]
I got stuck, so I got around it by navigating to the folder containing the pip executable and running it there using a full path for the shreddit zip instead.  So if this would cause it to install incorrectly, then maybe?

The place I know I'm stuck is the error I posted above with shreddit.yml having issues on L14,C1.  The line setting how many hours to keep.

I did add my user/pass to the file, and have pasted the file below with my details removed.

```
---
# Login details for Reddit. Fill out if you don't wish
# to be prompted for a login every time you run Shreddit.
### NOTE: This may be deprecated as you can specify in praw.ini instead
username:<redacted>
password:<redacted>

# How many hours of comments you want to keep
# 24 hours in a day,
# 168 hours in a week,
# 672 hours in two fortnights,
# 720 hours in a month (30 days),
# 8766 hours in a year (365.25 days)
hours: 24

# Max score, higher than this and it'll be kept.
max_score: 100

# Options: new, top, controversial, more?
sort: new

# Enables print statements to notify you of what's going on
verbose: True

# Removes your vote before deleting the item
clear_vote: False

# Options: comments, submitted, overview
# See: https://github.com/mellort/reddit_api/blob/master/reddit/objects.py#L359
# Overview: both submissions and comments. Comments / Submitted are as expected
item: overview

# Anything in this list won't be deleted, coma delimited
# spaces should work as .strip() is called after splitting
# on comma.
# whitelist: [AskScience, TheCulture, redditdev, programming, charity, netsec]
whitelist:

# If you want any specific posts to be whitelisted stick 'em in here
whitelist_ids: []

# If you set this then no editing or deleting will be done
# but the output from the program will be shown as an example
trial_run: False

# Don't delete but *do* edit, could prove... interesting to see a comment
# with 5000 upvotes and it's just a lorem ipsum!
edit_only: False

# Ignore distinguished comments.
whitelist_distinguished: True

# Ignore gilded (gold) comments
whitelist_gilded: True

# Delete everything older that this date, **This ignores whitelists**.
# Can be used as a second deletion, as in "delete items older than 24 hours
# except on whitelisted subreddits but after 3 months delete everything.
nuke_hours: 720

# Save a copy to disk of comments and posts before deleting them.
keep_a_copy: False
save_directory: /tmp

# Replacement text format
# Defines what you want to edit deleted content with pre-deletion (to ensure
# it's not saved in their database).
# Default: Random string. But this can be detected as spam in some cases.
# options: [random, dot, "user entered string"]
replacement_format: random

# Debug level, how much output you want
# See: https://docs.python.org/3/library/logging.html#logging-levels
debug: DEBUG

# Define your own wordlist to use as substitution text when
# replacement_format == random
wordlist: []

# Batch cooldown
# This controls how long (in seconds) to wait between each set of 1000 deletions.
batch_cooldown: 10

# vim: syntax=yaml ts=2
```

**Comment by x89** [comment]
Does your password contain symbols, like quotations? If it does could you perhaps try enclosing it in either double quotes or single quotes? Just a haunch but it may solve the issue.

**Comment by joebywan** [comment]
No it doesn't, basic alphanumeric.

**Comment by x89** [comment]
It does seem suspiciously similar to https://github.com/x89/Shreddit/issues/64 — is any information in there relevant? Can you put quotes around it so it's as follows (taking note of `"` double quotations):

```yaml
### NOTE: This may be deprecated as you can specify in praw.ini instead
username: "user"
password: "pass"
```

**Comment by joebywan** [comment]
That did it.  Issue was there was no space between the colon & the username & password.

Also it had issues with me trying to use an empty whitelist on line 37.  So I'll have to just put in a subreddit that I've not posted in before.

Thanks for the help :)

**Comment by x89** [comment]
Glad you got it sorted!
