### ISSUE TITLE
ImportError: No module named errors

### ISSUE THREAD

**Issue by HH0718** [x89/Shreddit#73]
Not really sure why this is happening. I have tried uninstalling, reinstalling, manually importing modules. Every time I run Shreddit windows or Mac OS X I get errors. Any suggestions?

```
Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 9, in <module>
    load_entry_point('shreddit==2.0.0', 'console_scripts', 'shreddit')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.12-intel/egg/shreddit/app.py", line 8, in <module>
  File "build/bdist.macosx-10.12-intel/egg/shreddit/shredder.py", line 12, in <module>
ImportError: No module named errors
```

```
Traceback (most recent call last):
  File "shredder.py", line 12, in <module>
    from praw.errors import (InvalidUser, InvalidUserPass, RateLimitExceeded,
ImportError: No module named errors
```

I have tried using python 2.7 and 3.5 with fresh installs of everything.

It just can't find the module named "errors"

Thanks for your help.

**Comment by x89** [comment]
At a guess that's because there's no `praw` module. Can you run either `pip install praw` or use:

```bash
python setup.py build
python setup.py install
```

And see if either of those work?

**Comment by HH0718** [comment]
Good morning! Thanks for the fast response. I have verified that the praw module is installed... but I do believe there is something wrong.

```
Requirement already satisfied: praw in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/praw-4.0.0rc3-py3.5.egg
Requirement already satisfied: decorator<4.1,>=4.0.9 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/decorator-4.0.10-py3.5.egg (from praw)
Requirement already satisfied: prawcore<0.4,>=0.3.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/prawcore-0.3.0-py3.5.egg (from praw)
Requirement already satisfied: requests>=2.3.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.12.1-py3.5.egg (from praw)
Requirement already satisfied: six==1.10 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/six-1.10.0-py3.5.egg (from praw)
Requirement already satisfied: update_checker>=0.12 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/update_checker-0.15-py3.5.egg (from praw)
```

```
Requirement already satisfied: praw in /Library/Python/2.7/site-packages/praw-4.0.0rc3-py2.7.egg
Requirement already satisfied: decorator<4.1,>=4.0.9 in /Library/Python/2.7/site-packages/decorator-4.0.10-py2.7.egg (from praw)
Requirement already satisfied: prawcore<0.4,>=0.3.0 in /Library/Python/2.7/site-packages (from praw)
Requirement already satisfied: requests>=2.3.0 in /Library/Python/2.7/site-packages/requests-2.12.1-py2.7.egg (from praw)
Requirement already satisfied: six==1.10 in /Library/Python/2.7/site-packages (from praw)
Requirement already satisfied: update_checker>=0.12 in /Library/Python/2.7/site-packages (from praw)
```

```
$ python setup.py build
running build
running build_py

```

Is it possible that Shreddit is being installed in the wrong directory?

**Comment by x89** [comment]
Interesting, it could be (I'm not familiar with the OS X architecture) but it looks as if it's installed correctly.

Is this being installed in a virtual environment or globally? It seems for whatever reason that the `praw.errorss` module can't be found (which I'd assume is because `praw` itself can't be found).

**Comment by scott-hand** [comment]
@HH0718 Try removing the version numbers from requirements.txt, then running your `pip -r` command on it with additional `--force-reinstall --upgrade` flags. Then reinstall with `python setup.py install`. I tried installing Shreddit on a fresh VM, got your errors issue, and this fixed it for me.

@x89 I'm going to remove the frozen packages at least until everything settles with the refactor, so that I can test the install on a fresh VM later. You talked about adding me as a contributor, and if so, I'll clone this main repo and create a branch for myself for it. I'd like to also get a PyPI version for easy Mac and Unix installations as well as look into a Pyinstaller built release for easy Windows distribution.

**Comment by x89** [comment]
That all sounds good to me, getting it easily installable on Windows and Mac really isn't my speciality so I appreciate it! I'll start using branches for changes myself as I've been slacking and just working in master for the most part being the only contributor.

I can spin up Linux / FreeBSD VMs myself to test easily enough, if you want any assistance just holler. :)

Added you as contributor.

**Comment by scott-hand** [comment]
Sounds good. I'm wrapping up on some work to get it into PyPI. I'm still going to work out of my fork and PR it to keep things simple, but I'll @x89 in each PR to let you know when I do it. I realized I had my info in the setup.py info, but it needs to be updated to represent the original repo. Do you have any issues with your name and email being in there?

**Comment by x89** [comment]
No issue at all. Thanks!

**Comment by HH0718** [comment]
@scott-hand @x89 Sorry for the late reply. I have been traveling all day for business and now I get to play a little. Thank you both very much for taking the time to help.

@scott-hand I will try to do as you recommended and let you know.

FYI, I didn't get any sleep last night and I am going on 32 hours.... So my response may come tomorrow evening USA CST.

Once again, thank you both for your help.

**Comment by x89** [comment]
Get some sleep man, I'm sure Shreddit will be here in the morning!

**Comment by HH0718** [comment]
@x89 Will do but first I have to eat... then sleep. While I wait for my room service, I will attempt this.

**Comment by HH0718** [comment]
@scott-hand viola. You sir are a gentleman and a scholar. It worked.

As someone who is learning python. I am interested to find out why it didn't work prior to changing requirements.txt

If you have the time could you post a TL;DR version of why this occurred? and more importantly how you came to the conclusion that deleting the versions would fix it?

@x89 This is a great program. Hopefully, I will be able to contribute to it when I become proficient.

**Comment by scott-hand** [comment]
@HH0718 I actually don't really know specifics. I had lots of similar issues with frozen dependencies earlier and figured that this might help. I suspect it has something to do with frozen dependencies not playing well with `pip install` from a zip, especially if you had already installed PRAW4 at some point. I did quite a bit of fresh VM testing on the latest PyPI uploaded version with the current set of frozen requirements and everything seems to work nicely.

**Comment by mbreedlove** [comment]
I'm having this same issue on OS X. I've tried removing version numbers from requirements.txt then running `pip install -r requirements.txt --force-reinstall --upgrade` then re-running `python setup.py install`, where everything runs successfully. get_secret.py still fails when importing from praw.errors, though.

**Comment by skath** [comment]
Why is this closed? 

I see the workaround, but the failure is still caused by incorrect requirements in both your requirements.txt and setup.py. Seems like the Right Thing is to leave the issue open until you sort out your required versions. 

I'm pretty sure praw>=4 doesn't have a module named errors anymore. 

> [PRAW4 is completely backwards incompatible.](https://www.reddit.com/r/redditdev/comments/4bvp73/praw_4_beta_feedback_desired/)

I was able to workaround only by specifying praw<4 in setup.py.

```
diff --git a/setup.py b/setup.py
index 03b7f6b..7a19497 100644
--- a/setup.py
+++ b/setup.py
@@ -24,7 +24,7 @@ setup(
                  "Intended Audience :: End Users/Desktop",
                  "Programming Language :: Python"],
     packages=["shreddit"],
-    install_requires=["arrow", "backports-abc", "praw", "PyYAML", "requests", "six", "tornado"],
+    install_requires=["arrow", "backports-abc", "praw<4", "PyYAML", "requests", "six", "tornado"],
     package_data={"shreddit": ["shreddit.yml.example"]},
     entry_points={
         "console_scripts": [
```

**Comment by scott-hand** [comment]
@skath It was closed because I had last dealt with it on the 28th and PRAW V4 went live on PyPI on the 29th, and I didn't know when I closed it on the 30th.
