### ISSUE TITLE
Setting edit_only=True seems to get you banned from certain subreddits

### ISSUE THREAD

**Issue by brmc** [x89/Shreddit#76]
I have no reason to suspect edit_only=True is the culprit other than intuition, but i imagine it is tripping a bot detector.  It is the only flag from the default yml that i changed.  If that's not it, then shreddit could be problematic for some users.  

I'm just experimenting on a garbage account, so it doesn't really matter, but so far i've been banned from /r/worldnews and /r/gadgets

And for what it's worth, here's the rest of the config yml:

hours: 0
max_score: 99999999
sort: new
verbose: True
clear_vote: False
item: overview
whitelist: [AskScience, TheCulture, redditdev, programming, charity, netsec]
whitelist_ids: []
multi_blacklist: []
multi_whitelist: []
trial_run: False
edit_only: True
whitelist_distinguished: True
whitelist_gilded: True
nuke_hours: 0
keep_a_copy: False
save_directory: /tmp
replacement_format: random
debug: DEBUG
wordlist: []
batch_cooldown: 10

**Comment by brmc** [comment]
banned from /r/technology

**Comment by x89** [comment]
Could well be people viewing your posts and reporting them as spam?

**Comment by brmc** [comment]
I doubt it.  I can't remember the last time I commented in /r/gadgets, so it's unlikely that someone stumbled on a comment several months old within the timespan that the script has been running.

Even if that is the case, I think it's something that should be pointed out as a potential hazard to unsuspecting users

**Comment by brmc** [comment]
confirmed: "we got an automod notification from it because one of the words triggers an automod filter."

apparently the word was "jews"

**Comment by x89** [comment]
The randomness of the editing!

You should be able to set it to a string or lorem ipsum to get past that.

**Comment by brmc** [comment]
banned from /r/history too

and according to one mod, the mass editing/deleting triggers a spam warning

**Comment by x89** [comment]
Interesting.

I don't particularly want to get into a war with automod but perhaps a
random timed delay between editing and deleting could do the trick.

Do you know if automod notices if your edit cutoff time is significant? A
month or something like that, does it still notice?

I can take a look at automod's source code tomorrow if it's open source and
see if there's a solution that doesn't step on any toes and also keeps
accounts unbanned.

**Comment by brmc** [comment]
I don't know the specifics, but I do know automod is highly configurable, so it's probably going to be on a case-per-case basis.

one possible strategy might be to traverse and edit/delete the comments in some non-chronological order (e.g., deleting only one comment from a sub for however-many-cycles as long as available comments permit)

**Comment by scott-hand** [comment]
@x89 In the meantime, I'm going to push an update tonight that replaces the wordlist edit with some static lorem ipsum text embedded in the .py file. There's no real reason to be tricky and make it super random.

**Comment by x89** [comment]
The reason for using a wordlist is so the edited text isn't always the same, it's a subtle and perhaps unimportant point but I didn't want somebody searching the DB for single one phrase to find every user that of Shreddit — hence the randomisation.

I suppose they could use user agent or OAuth or some other signature to detect it but that was my thinking anyway.

**Comment by scott-hand** [comment]
I get the reasoning. Do you think it would be sufficient to take some static lorem ipsum text and scramble the words?

**Comment by scott-hand** [comment]
To be quite honest though, I never understood the "edit but don't delete" functionality, so I might be missing the point a bit.

**Comment by x89** [comment]
I considered removing it at one point, but I don't want to remove a feature others rely upon (the code's also a bit fiddly dealing with basically three timestamps, already-edited, to-be-edited and not-to-be-edited).

It's probably fine to just use some generic lorem ipsum, perhaps with a config option to overwrite it with some generic text (it originally just edited everything with "I have been Shreddited for privacy.").

This line was allowing that https://github.com/x89/Shreddit/blob/master/shreddit.yml.example#L79

**Comment by scott-hand** [comment]
Alright I'll submit a PR with a generic lorem ipsum paragraph, scrambled on each comment to prevent a single comment signature for shreddit and wait for you to approve and merge.

**Comment by brmc** [comment]
update: My account has been suspended due to this script.

**Comment by scott-hand** [comment]
That's odd. I wrote a [bot](https://github.com/scott-hand/monologue-bot) that I've used to post literally tens of thousands of nonsense comments to reddit and then edit/delete with this script and never had issues, to include shadow bans.

Was any other information given?

**Comment by brmc** [comment]
No, not really. Like I mentioned earlier, one mod noticed due to the word
Jews(he didn't ban me though), and another said it was due to editing.
one mod from /r/technology even said they'd lift the ban if i use a script
that does exactly what your script does =-/

Here is the full text from Reddit:

Your account has been suspended
<https://reddit.zendesk.com/hc/en-us/articles/205687686> from Reddit for
spamming the site. The suspension will last for 3 day(s).

Be sure to read up on the Reddit content policy
<https://www.reddit.com/help/contentpolicy> to make sure you understand the
rules for participating on Reddit.

If you believe your account has been suspended in error, you can contact us
by replying to this message.

**Comment by x89** [comment]
Hmm, so an actual Reddit wide suspension for creating test posts - I wonder
what differs between your and @scott-hand's mass comments.

**Comment by scott-hand** [comment]
Well I'm glad it's only for a few days, but it is concerning. Shreddit operates within Reddit API ToS and provides a suitable user agent to identify itself.

Might be something to try to talk to someone about, but I don't have any connection with reddit admins so I wouldn't know where to begin.

**Comment by scott-hand** [comment]
Closing this because the feature was removed.
