### ISSUE TITLE
Upgrade to PRAW 4

### ISSUE THREAD

**Issue by x89** [x89/Shreddit#80]
Pinging @scott-hand.

Okay so I've made a `praw4` branch but I can immediately see the difficulties. `praw.errors` I suppose should be replaced with `praw.exceptions` if at all, it may be that just catching the long-names `praw.whatever.SomeException` works as well.

As I think you alluded to… https://github.com/praw-dev/praw/tree/praw4#quickstart there's a big problem here with OAuth being required and to be readable before even initialising the Reddit object. That's going to be fun.

I propose using the praw4 branch at least for making shreddit working praw4, it won't be being merged until there's a user friendly easy way for OAuth to be set up for the user.

I'm going to keep digging around with my own client details and see what else is broken.

**Comment by scott-hand** [comment]
@x89 I should have mentioned that I already have one going. Let me push it to my fork, one moment. It seems to work fine. Still doesn't delete more than 1000 comments but I'll work on that eventually.

**Comment by scott-hand** [comment]
[Here](https://github.com/scott-hand/Shreddit/tree/praw4) is my branch. Here's a few things I changed to make it work:

* I went ahead and took out edit_only. Given that someone said it got them suspended, I'm willing to cut it since it's not something that I think adds value. If you disagree, I can always add it back in but since we're overhauling things, now's as good a time as any.
* Creds are now solely in praw.ini and not in shreddit.yml. PRAW4 manages multiple credential sets much better. It has copied boto3 in multiple useful ways and this is one of them.
* I used the OAuth Script approach. It means that people have to make applications in their reddit settings page for each account, *but* it also means no redirecting and exchanging of refresh tokens. You do it once (with a guide linking to the app settings page), pop the client ID and secret into the praw.ini, and you don't have to worry about it again.

**Comment by scott-hand** [comment]
As for hosting as a web app, I have experience doing Angular 1.5 + ES6 frontends on top of Python backends, so I *could* work on that. The problem is that I'm not sure if I want to commit to hosting and operating it, especially given how super easy it is to use the script OAuth mode.

**Comment by x89** [comment]
* Getting rid of edit_only is fine, I don't think it really needs to be continued.
* I was just looking at my own, duplicate!, praw4 branch and it wasn't reading from praw.ini neither in the local directory nor `~/.config` for some reason. I'll compare with yours to see what I had wrong.
* That's a nicer touch (as are the speed improvements). If I understand correctly that means no more listening on localhost:port for a response to some user-input URL?

Regarding the hosting, yes it'd be a commitment. I'm happy to pay for the infrastructure costs and continue working on Shreddit but I'm also not keen to work on the frontend stuff long-term, though I may just bite the bullet at some point and get it done. That'd certainly make the OAuth stuff user-friendly.

Good work!

**Comment by scott-hand** [comment]
Yeah no more listening. It stops really being OAuth and is basically just an API key.

**Comment by scott-hand** [comment]
I'll finish up documentation tomorrow and have a candidate release hopefully ready. Sorry I didn't post something about working on a branch, I only made it a few hours back and had planned to notify you when I had a working version.

**Comment by scott-hand** [comment]
@x89 Take a look at my praw4 branch and let me know what you think. I updated the README to cover PRAW4 usage.

**Comment by x89** [comment]
So @scott-hand I've looked at your praw4 branch and I think you need `prawcore<0.4,>=0.3.0` somewhere as a dependency of `praw>=4` — I ran into that while running setup.py.

The `shreddit -g` might need some looking at as well:

```python
Writing shreddit.yml file...
Traceback (most recent call last):
  File "./.venv/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.0', 'console_scripts', 'shreddit')()
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/app.py", line 24, in main
TypeError: write() argument must be str, not bytes
```

The documentation looks mostly fine!

**Comment by scott-hand** [comment]
Ok @x89 , fun with PRAW again. Their Github version wants prawcore 0.4.x but their PyPI version wants prawcore 0.3.x. And since the current PyPI version of prawcore is 0.4.x we have to force both of them in requirements.txt for now. I'm going to make an issue in their Github about it. Seems to play nice with Python 3 now:

```bash
$ virtualenv /tmp/shreddit -p /usr/bin/python3.5
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /tmp/shreddit/bin/python3.5
Also creating executable in /tmp/shreddit/bin/python
Installing setuptools, pip, wheel...done.

$ source /tmp/shreddit/bin/activate

$ pip install -r requirements.txt
Collecting arrow==0.9.0 (from -r requirements.txt (line 1))
Collecting decorator==4.0.10 (from -r requirements.txt (line 2))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Collecting praw==4.0.0 (from -r requirements.txt (line 3))
  Using cached praw-4.0.0-py2.py3-none-any.whl
Collecting prawcore==0.3.0 (from -r requirements.txt (line 4))
  Using cached prawcore-0.3.0-py2.py3-none-any.whl
Collecting PyYAML==3.12 (from -r requirements.txt (line 5))
Collecting requests==2.12.1 (from -r requirements.txt (line 6))
  Using cached requests-2.12.1-py2.py3-none-any.whl
Collecting six==1.10.0 (from -r requirements.txt (line 7))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting backports-abc==0.4 (from -r requirements.txt (line 8))
  Using cached backports_abc-0.4-py2.py3-none-any.whl
Collecting tornado==4.3 (from -r requirements.txt (line 9))
Collecting update-checker==0.15 (from -r requirements.txt (line 10))
  Using cached update_checker-0.15-py2.py3-none-any.whl
Collecting wheel==0.24.0 (from -r requirements.txt (line 11))
  Using cached wheel-0.24.0-py2.py3-none-any.whl
Collecting python-dateutil (from arrow==0.9.0->-r requirements.txt (line 1))
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, arrow, decorator, requests, prawcore, update-checker, praw, PyYAML, backports-abc, tornad                                                          o, wheel
  Found existing installation: wheel 0.30.0a0
    Uninstalling wheel-0.30.0a0:
      Successfully uninstalled wheel-0.30.0a0
Successfully installed PyYAML-3.12 arrow-0.9.0 backports-abc-0.4 decorator-4.0.10 praw-4.0.0 prawcore-0.3.0 python-dateutil-2.6.0 requests-2.1                                                          2.1 six-1.10.0 tornado-4.3 update-checker-0.15 wheel-0.24.0

$ python setup.py install
running install
running bdist_egg
running egg_info
...
Finished processing dependencies for shreddit==6.0.0

$ shreddit -g

$
```

**Comment by scott-hand** [comment]
On second though, I just removed the explicit prawcore requirement so that praw can manage it itself.

**Comment by x89** [comment]
```python
Traceback (most recent call last):
  File "/usr/lib64/python3.5/configparser.py", line 843, in items
    d.update(self._sections[section])
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/napalm/scott-shreddit/.venv/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.0', 'console_scripts', 'shreddit')()
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/app.py", line 44, in main
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/shredder.py", line 27, in __init__
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/shredder.py", line 79, in _connect
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/praw-4.0.0-py3.5.egg/praw/reddit.py", line 105, in __init__
    **config_settings)
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/praw-4.0.0-py3.5.egg/praw/config.py", line 64, in __init__
    self.custom = dict(Config.CONFIG.items(site_name), **settings)
  File "/usr/lib64/python3.5/configparser.py", line 846, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'default'
```

I'm getting this atm when I run your praw branch after a straight copy of my previously existing praw.ini and shreddit.yml config files, and when I run `shreddit -g` I'm getting the following traceback if the config files don't already exist:

```python
Writing shreddit.yml file...
Traceback (most recent call last):
  File "/home/napalm/scott-shreddit/.venv/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.0', 'console_scripts', 'shreddit')()
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/app.py", line 24, in main
TypeError: write() argument must be str, not bytes
```

**Comment by scott-hand** [comment]
Looks like Python 3.5, what does your `pip freeze` output say?

And bear in mind that you will need new praw.ini and shreddit.yml files. While it's not ideal to require this, PRAW4 breaks backwards compatibility on what it requires for credential information.

**Comment by scott-hand** [comment]
@x89 I'm also really confused at how `pkg_resources.resource_string("shreddit", "shreddit.yml.example")` is returning a bytes result.

**Comment by scott-hand** [comment]
@x89 I just pushed another commit. I didn't know this, but `resource_string` should be called `resource_bytes` in Python 3. Oh well, it's now handled correctly.

**Comment by x89** [comment]
Am I missing something or does `oauth_refresh_token` not need to be fetched in PRAW4?

I'm getting 403s with the client / secret input as per the README.md in your praw4 branch. At least when I was doing in previously I used the client + secret, then had to listen on the callback URL to get a refresh OAuth token which was finally appended to praw.ini.

**Comment by scott-hand** [comment]
Correct. Read the PRAW4 documentation notes on OAuth in script mode for more info. All you need is ID and secret, no refresh token needed.

**Comment by x89** [comment]
Hmm, I wonder why the 403 then… Let me investigate further.

**Comment by x89** [comment]
I'll read over the notes as well, I'm curious as to how they reworked permissions in that case (since requesting the OAuth token requested the Reddit App give you an array of permissions, I'm not seeing a permissions per Reddit App section).

**Comment by scott-hand** [comment]
Yeah I think it just has full access. It's basically an API key.

**Comment by x89** [comment]
Weird, I just get the following. With nothing but `client_id` and `client_secret` filled out after running `shreddit -g`.

```pytb
Traceback (most recent call last):
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/shredder.py", line 80, in _connect
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/praw-4.0.0-py3.5.egg/praw/models/user.py", line 41, in me
    user_data = self._reddit.get(API_PATH['me'])
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/praw-4.0.0-py3.5.egg/praw/reddit.py", line 307, in get
    data = self.request('GET', path, params=params)
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/praw-4.0.0-py3.5.egg/praw/reddit.py", line 391, in request
    params=params)
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/prawcore-0.3.0-py3.5.egg/prawcore/sessions.py", line 124, in request
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/prawcore-0.3.0-py3.5.egg/prawcore/sessions.py", line 75, in _request_with_retries
prawcore.exceptions.Forbidden: received 403 HTTP response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/napalm/scott-shreddit/.venv/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.0', 'console_scripts', 'shreddit')()
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/app.py", line 44, in main
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/shredder.py", line 27, in __init__
  File "/home/napalm/scott-shreddit/.venv/lib/python3.5/site-packages/shreddit-6.0.0-py3.5.egg/shreddit/shredder.py", line 82, in _connect
shreddit.util.ShredditError: 'Bad OAuth credentials'
```

**Comment by scott-hand** [comment]
Oh, you also have to provide username and password. I have no idea why, given that you're providing a secret already.  ¯\\\_(ツ)_/¯ Thanks Reddit API / PRAW

**Comment by x89** [comment]
Okay that seems to be it working, seems a bit like one step forward and two steps back if you're going to require both a client id and secret *and* the user and password!  
What on earth are they thinking?

But yes I've got it working now with my username and password. I suppose at least that's easier than the localhost listening method.

**Comment by x89** [comment]
We're 100% sure that this uses OAuth and not cookie/pw auth if those details are in there, yeah?

**Comment by scott-hand** [comment]
Yep. PRAW calls it a [script application](http://praw.readthedocs.io/en/latest/getting_started/authentication.html#script-application).

**Comment by x89** [comment]
As you accurately put it, ¯\_(ツ)_/¯.

That's the praw4 branch working at least. Just add an extra step in the https://github.com/scott-hand/Shreddit/tree/praw4#configuring-credentials section to say for scripts you need to fill in your username and password. Perhaps most will do that anyway but it's better to be explicit.

**Comment by scott-hand** [comment]
Done. I'll submit a PR
