### ISSUE TITLE
this tool is complete shit

### ISSUE THREAD

**Issue by NecroneUnderscore** [x89/Shreddit#81]
execution of 'shreddit':
Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: praw<4

**Comment by anlutro** [comment]
I agree but for unrelated reasons

**Comment by scott-hand** [comment]
Install the depedencies ya dingus.

@x89 As silly as this issue is, he might be raising a good point in that PRAW3 usage will only get more problematic as time goes on. Have you taken a look at my PRAW4 branch? I did some testing and it seems to work fine, I just want to make sure you think the documentation is sufficient.

**Comment by EricBisceglia** [comment]
@x89 please take @anlutro 's feedback into account instead of disregarding every user input you get.

Thanks in advance,
Eric B.

sent from my irccloud paid account

**Comment by scott-hand** [comment]
Yeah, "for unrelated reasons" is definitely some quality feedback from some of the brightest minds on the internet. 

sent from my web browser on a regular computer

**Comment by moopie** [comment]
please be civil guys, this is a serious project not some irc channel

**Comment by x89** [comment]
OP is free to re-make the issue when he's calmed down!

"This tool is complete shit" with what was originally just "learn to not depend on libraries" as a comment is not an issue worth considering.
