### ISSUE TITLE
Add whitelist/blacklist for private multireddit

### ISSUE THREAD

**Issue by slcott** [x89/Shreddit#89]
I got this error when trying to whitelist a private multreddit. Can we add this feature?

```
Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/shreddit/app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "/usr/local/lib/python3.6/site-packages/shreddit/shredder.py", line 42, in __init__
    multireddit = self._r.get_multireddit(username, multiname)
AttributeError: 'Reddit' object has no attribute 'get_multireddit'
```

**Comment by scott-hand** [comment]
Good catch. It was still using the PRAW3 syntax. I just pushed a commit to fix it, let me know if that helps.

**Comment by slcott** [comment]
No.

I tried installing using `pip3 install -U shreddit`.
Does pip install the latest? Is it 6.0.6?
Anyway, I tried cloning the master and manually install.

Same output:
```
Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.6', 'console_scripts', 'shreddit')()
  File "/usr/local/lib/python3.6/site-packages/shreddit/app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "/usr/local/lib/python3.6/site-packages/shreddit/shredder.py", line 42, in __init__
    multireddit = self._r.get_multireddit(username, multiname)
AttributeError: 'Reddit' object has no attribute 'get_multireddit'
```

**Comment by scott-hand** [comment]
I haven't uploaded it to PyPI, but I'll go ahead and do that so you can test it out with `pip install`.

**Comment by slcott** [comment]
I also installed manually from master and it did not work.

Maybe I can figure out what's wrong tomorrow and send you a PR.

**Comment by slcott** [comment]
I looked into your code and praw and it looked correct, which left one possibility.  I completely uninstalled shreddit and reinstalled manually. My install wasn't the latest for some weird reason.
