### ISSUE TITLE
Trial run upgrades?

### ISSUE THREAD

**Issue by miketwo** [x89/Shreddit#90]
#### Protect clear_vote()
Should this line be wrapped with `if not self._trial_run`?
```
if self._clear_vote:
    try:
        item.clear_vote()            <------
    except BadRequest:
        self._logger.debug("Couldn't clear vote on {item}".format(item=item))
```
#### Protect save_item()?
Maybe this should be wrapped as well, so it just pretends to save locally?
```
def _save_item(self, item):
    with open(os.path.join(self._save_directory, "{}.json".format(item.id)), "w") as fh:    <----
        ...
```

#### Mock objects instead
Alternatively, a safer way might be to build mocking directly into the item access. Something like:
```
if self._trial_run:
	to_delete = [mock.Mock(spec=item) for item in items]
else
	to_delete = [item for item in items]
```
That way, you're never dealing with the real objects in a trial run, so you can call whatever on them and it'll be safe.

**Comment by x89** [comment]
772df35c68a6782b2bd733801458023545977166

I've implemented the first of your suggestions as the quickest solution, votes won't be cleared on trial runs anymore.
