### ISSUE TITLE
I have to add Shreddit manually to PATH

### ISSUE THREAD

**Issue by roydbtR** [x89/Shreddit#95]
The Shreddit command line isn't working for me so I have to add it to the PATH but where is the dir folder of Shreddit?

**Comment by scott-hand** [comment]
`pip install` should drop it with other python tools like `ipython` and `virtualenv`. If you installed it into a virtualenv, it will be in the bin folder there, if not it will be in the global python binary folder (`/usr/local/bin` on Ubuntu for example)

Did you install via pip install?

**Comment by roydbtR** [comment]
Yes and I am using Windows 10

**Comment by ardeaf** [comment]
If you're on windows 10 did you install with an elevated command prompt?

**Comment by x89** [comment]
Closing due to lack of responses, if you have issues feel free to comment more.

I don't have a Windows machine to hand to test.
